config/routes.rb
Dp::Application.routes.draw do

  get "image/new"

  get "image/create"

  resources :users do
    member do
      get 'follow'
    end
    collection do
      get 'search'
      post 'search'
    end
    resources :messages, :only => [:create, :destroy, :show, :new]
    resources :images
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts, :only => [:create, :destroy, :update]
  resources :comments, :only => [:create, :destroy, :update]

  match "/inbox" => "messages#index"
  match "/outbox" => "messages#sent"
  match "/news" => "pages#news"
  match "/signup" => "users#new"
  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy"

  root :to => 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, :class_name => 'User', :foreign_key => 'follower_id'
  belongs_to :following, :class_name => 'User', :foreign_key => 'following_id'
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  belongs_to :recipient, :class_name => 'User', :foreign_key => 'recipient_id'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  def importance
  end
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password, :password_confirmation
  attr_accessor :password

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 }

  before_save :encrypt_password

  has_many :posts
  has_many :comments
  has_many :images
  has_many :followers, :class_name => 'Follow', :foreign_key => 'following_id'
  has_many :following, :class_name => 'Follow', :foreign_key => 'follower_id'
  has_many :messages_sent, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :messages_received, :class_name => 'Message', :foreign_key => 'recipient_id'

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def image_url
    Image.find(self.image_id).image.url
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(params[:comment]);
    comment.save
    redirect_to root_path
  end

  def update
  end
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
  def show
    f = Follow.new(:follower => current_user, :following => params[:id])
    f.save
  end

  def destroy
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @title = "New Image"
  end

  def create
    @p = Image.new(params[:image])
    @p.user = current_user
    @p.save
    redirect_to user_path(current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = current_user.messages_received
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @recipient = User.find(params[:user_id])
  end

  def create
    message = Message.new(:sender => current_user, :recipient_id => params[:user_id], :message => params[:message][:message])
    message.save
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      redirect_to news_path
    end
  end

  def news
    @title = "News"
    @posts = Post.order("id DESC").all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = Post.new(:user => current_user, :body => params[:post][:body])
    post.save
    redirect_to root_path
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign In"
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid Login"
      @title = "Sign In"
      render 'new'
    else
      sign_in user
      redirect_to news_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @title = "Profile"
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
    @title = "Edit Profile"
  end

  def new
    @user = User.new
    @title = "Sign Up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def follow
    f = Follow.new(:follower => current_user, :following_id => params[:id])
    f.save
    redirect_to user_path(params[:id])
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Daddy Paradise"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follow/create.html.erb
<h1>Follow#create</h1>
<p>Find me in app/views/follow/create.html.erb</p>

app/views/follow/destroy.html.erb
<h1>Follow#destroy</h1>
<p>Find me in app/views/follow/destroy.html.erb</p>

app/views/images/create.html.erb
<%= image_tag @p.image.url %>

app/views/images/new.html.erb
<h1>Fuck You</h1>
<%= form_for :image, :url => images_path, :html => { :multipart => true } do |f| %>
  <%= f.file_field :image %>
  <%= f.submit "Save Image" %>
<% end %>

app/views/messages/create.html.erb
<h1>Message#create</h1>
<p>Find me in app/views/message/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Message#destroy</h1>
<p>Find me in app/views/message/destroy.html.erb</p>

app/views/messages/index.html.erb
<h2>Inbox | <%= link_to "Outbox", outbox_path %></h2>
<table cellspacing="5">
  <% @messages.each do |m| %>
    <tr>
      <td width="40"><%= image_tag m.sender.image_url, :width => 30 %></td>
      <td width="150"><%= link_to m.sender.name, user_message_path(current_user,m) %></td>
      <td width="150"><%= m.created_at.strftime("%A %B %d, %Y") %></td>
    </tr>
  <% end %>
</table>

app/views/messages/new.html.erb
<h2>Send a message to <%= link_to @recipient.name, user_path(@recipient) %></h2>
<%= form_for :message, :url => user_messages_path(@recipient) do |f| %>
  <%= f.label "What do you want to say" %><br/>
  <%= f.text_area :message, :cols => 70, :rows => 15 %><br/>
  <%= f.submit "Send Message" %>
<% end %>

app/views/messages/show.html.erb
<%= @message.message %>
<%= form_for :message, :url => user_messages_path(@message.sender) do |f| %>
  <%= f.label "What do you want to say" %><br/>
  <%= f.text_area :message, :cols => 70, :rows => 10 %><br/>
  <%= f.submit "Send Message" %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :autocomplete => :off %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation, :autocomplete => :off %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h2><%= image_tag @user.image_url %> <%= @user.name %></h2>
<%= link_to "Send a message", new_user_message_path(@user) %> |
<%= link_to "Follow " + @user.name, follow_user_path(@user) %>