config/routes.rb
Dp::Application.routes.draw do

  get "image/new"

  get "image/create"

  resources :users do
    member do
      get 'follow'
    end
    collection do
      get 'search'
      post 'search'
    end
    resources :messages, :only => [:create, :destroy, :show, :new]
    resources :images
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts, :only => [:create, :destroy, :update]
  resources :comments, :only => [:create, :destroy, :update]

  match "/inbox" => "messages#index"
  match "/outbox" => "messages#sent"
  match "/news" => "pages#news"
  match "/signup" => "users#new"
  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy"

  root :to => 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, :class_name => 'User', :foreign_key => 'follower_id'
  belongs_to :following, :class_name => 'User', :foreign_key => 'following_id'
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  belongs_to :recipient, :class_name => 'User', :foreign_key => 'recipient_id'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  def importance
  end
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password, :password_confirmation
  attr_accessor :password

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 }

  before_save :encrypt_password

  has_many :posts
  has_many :comments
  has_many :images
  has_many :followers, :class_name => 'Follow', :foreign_key => 'following_id'
  has_many :following, :class_name => 'Follow', :foreign_key => 'follower_id'
  has_many :messages_sent, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :messages_received, :class_name => 'Message', :foreign_key => 'recipient_id'

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def image_url
    Image.find(self.image_id).image.url
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(params[:comment]);
    comment.save
    redirect_to root_path
  end

  def update
  end
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
  def show
    f = Follow.new(:follower => current_user, :following => params[:id])
    f.save
  end

  def destroy
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @title = "New Image"
  end

  def create
    @p = Image.new(params[:image])
    @p.user = current_user
    @p.save
    redirect_to user_path(current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      redirect_to news_path
    end
  end

  def news
    @title = "News"
    @posts = Post.order("id DESC").all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = Post.new(:user => current_user, :body => params[:post][:body])
    post.save
    redirect_to root_path
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @title = "Profile"
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
    @title = "Edit Profile"
  end

  def new
    @user = User.new
    @title = "Sign Up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def follow
    f = Follow.new(:follower => current_user, :following_id => params[:id])
    f.save
    redirect_to user_path(params[:id])
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Daddy Paradise"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer_container">
  <div id="footer">Footer Stuff</div>
</div>

app/views/layouts/_header.html.erb
<div id="header_container">
  <div id="header">
    <span style="color:#6699cc">d</span><span style="color:orange">social</span>
    <% if signed_in? %>
      <div style="float:right;font-size:12px;color:white">Account Settings | <%= link_to "Log Out", logout_path %></div>
    <% else %>
      <div style="float:right;font-size:12px;color:white">Sign Up | <%= link_to "Log In", login_path %></div>
    <% end %>
  </div>
</div>

app/views/layouts/_left_menu.html.erb
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in
not logged in

app/views/layouts/_left_menu_user.html.erb
<div class="picture">
<table>
<tr>
<td><%= image_tag current_user.image_url, :width => 40 %></td>
<td>&nbsp;<%= link_to current_user.name, user_path(current_user) %></td>
</tr>
</table>
</div>
<%= link_to "Personal Messages", inbox_path, :class => "left_menu_link" %>
<%= link_to "Visitors", inbox_path, :class => "left_menu_link" %>
<%= link_to "Photos (" + current_user.images.size.to_s + ")", user_images_path(current_user), :class => "left_menu_link" %>
<%= link_to "Followers ("+current_user.followers.size.to_s+")", inbox_path, :class => "left_menu_link" %>
<%= link_to "Following ("+current_user.following.size.to_s+")", inbox_path, :class => "left_menu_link" %>

app/views/layouts/_menu.html.erb
<div id="menu_container">
  <nav id="menu">
    <ul class="main">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Log In", login_path %></li>
      <li><%= link_to "Sign Up", signup_path %></li>
    </ul>
  </nav>
</div>
<script>  
    (function($){  
  
        //cache nav  
        var nav = $("#menu");  
  
        //add indicators and hovers to submenu parents  
        nav.find("li").each(function() {  
            if ($(this).find("ul").length > 0) {  
  
                //show subnav on hover  
                $(this).mouseenter(function() {  
                    $(this).find("ul").stop(true, true).slideDown(150);  
                });  
  
                //hide submenus on exit  
                $(this).mouseleave(function() {  
                    $(this).find("ul").stop(true, true).slideUp(150);  
                });  
            }  
        });  
    })(jQuery);  
</script>  

app/views/layouts/_menu_home.html.erb
<div id="menu_container">
  <nav id="menu">
    <ul class="main">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Log In", login_path %></li>
      <li><%= link_to "Sign Up", signup_path %></li>
    </ul>
  </nav>
</div>
<script>  
    (function($){  
  
        //cache nav  
        var nav = $("#menu");  
  
        //add indicators and hovers to submenu parents  
        nav.find("li").each(function() {  
            if ($(this).find("ul").length > 0) {  
  
                //show subnav on hover  
                $(this).mouseenter(function() {  
                    $(this).find("ul").stop(true, true).slideDown(150);  
                });  
  
                //hide submenus on exit  
                $(this).mouseleave(function() {  
                    $(this).find("ul").stop(true, true).slideUp(150);  
                });  
            }  
        });  
    })(jQuery);  
</script>  

app/views/layouts/_menu_user.html.erb
<div id="menu_container">
  <nav id="menu">
    <ul class="main">
      <% if current_page?(news_path) %>
        <li><%= link_to "News Feed", news_path %></li>
      <% else %>
        <li><%= link_to "News Feed", news_path %></li>
      <% end %>
      <li><%= link_to "My Profile", user_path(@current_user) %></li>
      <li><%= link_to "Find Users", search_users_path %></li>
      <!--<li><%= link_to "Men's Health", root_path %></li>-->
    </ul>
  </nav>
</div>
<script>  
    (function($){  
  
        //cache nav  
        var nav = $("#menu");  
  
        //add indicators and hovers to submenu parents  
        nav.find("li").each(function() {  
            if ($(this).find("ul").length > 0) {  
  
                //show subnav on hover  
                $(this).mouseenter(function() {  
                    $(this).find("ul").stop(true, true).slideDown(150);  
                });  
  
                //hide submenus on exit  
                $(this).mouseleave(function() {  
                    $(this).find("ul").stop(true, true).slideUp(150);  
                });  
            }  
        });  
    })(jQuery);  
</script>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <title><%= title %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag '/assets/main.css', :media => 'screen' %>
</head>
<body>
<div id="main">
  <%= render 'layouts/header' %>
  <% if signed_in? %>
    <%= render 'layouts/menu_user' %>
  <% else %>
    <%= render 'layouts/menu' %>
  <% end %>
  <div id="content_container">
  <div id="content_padding">
  <div id="content">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <div id="left_menu">
      <% if signed_in? %>
        <%= render 'layouts/left_menu_user' %>
      <% else %>
        <%= render 'layouts/left_menu' %>
      <% end %>
    </div>
    <div id="main_content">
      <%= yield %>
    </div>
    <div class="clear">&nbsp;</div>
  </div><!-- End Div id="content" -->
  </div><!-- End Div id="content_padding" -->
  </div><!-- End Div id="content_container" -->
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div><!-- End Div id="main" -->
</body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>

app/views/pages/news.html.erb
<%= form_for :post, :url => posts_path, :html => { :method => "POST" } do |f| %>
  <%= render :partial => 'shared/post_form', :locals => { :f => f } %>
<% end %>

<% @posts.each do |post| %>
  <div class="post">
    <table>
      <tr>
        <td width="50" valign="top"><%= image_tag post.user.image_url, :width => 50 %></td>
        <td width="500">
          <table>
            <tr><td colspan="2"><%= link_to post.user.name, user_path(post.user) %></td></tr>
            <tr><td colspan="2"><%= post.body %></td></tr>
            <% post.comments.each do |comment| %>
              <tr><td width="20">&nbsp;</td><td><%= comment.comment %></td></tr>
            <% end %>
            <tr>
              <td width="20">&nbsp;</td>
              <td>
                <%= form_for :comment, :url => comments_path, :html => { :method => "POST" } do |c| %>
                  <%= c.text_field :comment %>
                  <%= c.hidden_field :post_id, :value => post.id %>
                  <%= c.hidden_field :user_id, :value => current_user.id %>
                <% end %>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="field">
  <%= f.label :body, "Speak and thou shalt be heard" %><br />
  <%= f.text_area :body, :autocomplete => :off, :cols => 60, :rows => 3 %><br/>
  <%= f.submit "Submit" %>
</div>